misinformation_task:
  description: >
    You are given a list of articles and their contents.
    You are to use these articles to determine if the given text is misinformation or not.

    # source_list:
    {source_list}

    Given Text: {given_text}
  expected_output: >
    Your output should include a score for the given text, indicating the likelihood of it being misinformation. (ranges from 0 to 1)
    You should also include a brief explanation of your analysis and the reasons for your score. (not more than 100 words)
  agent: misinformation_expert
