WebParsingTask:
  description: >
    Parse the webpage of {url} and extract the main text content, noting any images.
  expected_output: >
    A dictionary of weblink, title, content, image_url, date.
  agent: WebParsingTool
  tools: [WebParsingTool]
  
WebAnalyserTask:
  description: >
    Analyse the content and retrieve topics of the webpage and article body to be fact_checked.
  expected_output: >
    A dictionary of topic and article_body.
  agent: WebAnalyser
  tools: [WebParsingTool]

image_forgery_task:
  description: >
    Analyze the image {image} and detect signs of forgery, manipulation, or tampering.
  expected_output: >
    A classification of the image and a confidence score of the prediction.
  agent: image_forgery_expert
  tools: [detect_forgery_tool]
  async_execution: true

news_analysis_task:
  description: >
    Analyze the news article {article} and identify key information like entities, topics, and sentiment.
  expected_output: >
    A dictionary of news organisation name, topics, and sentiment analysis of the news article.
  agent: news_analyst

web_research_task:
  description: >
    Search the web on news articles about {article_title}
    Make sure the date range of the article is within a week of {article_date}.
  expected_output: >
    A list of 5 news articles most similar to the given article.
  agent: web_researcher

misinformation_task:
  description: >
    Get the a list of news articles most similar to {article_title}.
    Analyze the text data and detect signs of misinformation given external sources for validation.
    Identify if the given article is misinformation or not.
  expected_output: >
    An output of whether the article is misinformation or not.
  agent: misinformation_expert
  context: [web_research_task]

blacklist_task:
  description: >
    Blacklist a website that contains misinformation or fake news.
    Given a fake article, get its website domain name, author's name, article title, and date in the blacklist database.
  expected_output: >
    A dictionary of website domain name, author's name, article title, and date.
  agent: blacklister
  tools:[]


# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
