image_forgery_task:
  description: >
    Analyze these images {image_urls} and detect signs of forgery, manipulation, or tampering.
  expected_output: >
    A classification of the image and a confidence score of the prediction.
    A list of json of (image_url, classification, confidence_score).
  agent: image_forgery_expert
  async_execution: true

image_websearch_task:
  description: >
    Search for visually similar images to {image_urls} and retrieve related news articles.
    For each image, return the top similar images along with their article title, URL, and image thumbnail.

  expected_output: >
    A list of the top related articles, each containing the article title, URL, and image thumbnail.
    A list of json of image_url:(similar url, title, image_thumbnail)
  agent: image_websearch_expert
  async_execution: true

compile_forensics_task:
  description: >
    Compile the results of the image forgery and web search tasks.
  expected_output: >
    A list of dicts, with each dict containing the image_url, classification, confidence score, and related articles.
  agent: forensics_compiler
  context: [image_forgery_task, image_websearch_task]
  