query_db_task:
  description: >
    Query the database to retrieve the list of reliable sources and blacklisted sources.
    Return the two lists as a tuple (reliable_sources, blacklisted_sources) to the misinformation_auditor.
  expected_output: >
    An output of whether the article is misinformation or not.
  agent: database_checker

misinformation_task:
  description: >
    Given lists of reliable and blacklisted sources, classify the given article as misinformation or not.
    If the domain is not in the reliable sources or blacklisted sources, it is unreliable.
    Identify if the given article is 'misinformation', 'likely_credible' or 'unreliable'.
  expected_output: >
    An output of whether the article is misinformation or not. ['misinformation', 'likely_credible', 'unreliable']
  agent: auditor

# blacklist_task:
#   description: >
#     Blacklist a website that contains misinformation or fake news.
#     Given a fake article, get its website domain name, author's name, article title, and date in the blacklist database.
#   expected_output: >
#     A dictionary of website domain name, author's name, article title, and date.
#   agent: blacklister