web_research_task:
  description: >
    Search the web on news articles about {article_title}
    Make sure the date range of the article is within a week of {article_date}.
  expected_output: >
    A list of 5 news articles most similar to the given article.
  agent: web_researcher