web_parsing_task:
  description: >
    Parse the webpage of {url} and extract the main text content, noting any images.
  expected_output: >
    A dictionary of weblink, title, content, image_url, date.
  agent: web_parser

web_analyser_task:
  description: >
    Analyse the content and retrieve topics of the webpage and article body to be fact_checked.
  expected_output: >
    A dictionary of topic and article_body.
  agent: web_analyser